name: hadith_40
description: 40 hadith imam an-Nawawi
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Design
  scrollable_positioned_list: ^0.3.8
  flip_card: ^0.7.0
  cupertino_icons: ^1.0.8
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.6
  step_progress_indicator: ^1.0.2
  flutter_material_color_picker: ^1.2.0
  responsive_builder: ^0.7.1
  salomon_bottom_bar: ^3.3.2

  # Databases
  sqflite: ^2.4.2
  hive_flutter: ^1.1.0

  # System
  wakelock_plus: ^1.3.2
  vibration: ^3.1.3

  # Path
  path: ^1.9.1
  path_provider: ^2.1.5

  # Copy/Share
  clipboard: ^0.1.3
  share_plus: ^11.0.0

  # Notifications
  flutter_local_notifications: ^19.2.1

  # State management
  provider: ^6.1.5

  # Times
  intl: ^0.20.2
  timezone: ^0.10.1

  # Audio
  just_audio: ^0.10.3

  # Url
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/pictures/
    - assets/databases/
    - assets/audios/
    - assets/fonts/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_regular.ttf
    - family: SF Pro
      fonts:
        - asset: assets/fonts/sf_pro_regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
    - family: Hafs
      fonts:
        - asset: assets/fonts/hafs.ttf
    - family: Noto Naskh
      fonts:
        - asset: assets/fonts/noto_naskh_regular.ttf
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/scheherazade.ttf