name: hadith_40
description: 40 hadith imam an-Nawawi
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  path: ^1.8.3
  sqflite: ^2.3.0
  flutter_html: ^3.0.0-beta.2
  share_plus: ^7.1.0
  clipboard: ^0.1.3
  scrollable_positioned_list: ^0.3.8
  just_audio: ^0.9.34
  hive_flutter: ^2.0.0-dev
  flip_card: ^0.7.0
  provider: ^6.0.5
  flutter_material_color_picker: ^1.2.0
  wakelock_plus: ^1.1.1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/databases/
    - assets/audios/
    - assets/fonts/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
    - family: Noto Serif
      fonts:
        - asset: assets/fonts/noto_serif_regular.ttf
    - family: Noto Naskh
      fonts:
        - asset: assets/fonts/noto_naskh_medium.ttf
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/vazirmatn_regular.ttf
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/scheherazade_regular.ttf